### ISSUE TITLE
add a way for nodes to ask runner to initialize the gui parts (i.e. fastapi Depends)

### ISSUE THREAD

**Issue by raymondwjang** [Aharoni-Lab/cala#93]
I think you probably want to allow both: if someone explicitly passes `--gui` you should launch the gui, but they can also specify it in their config otherwise. To allow people to launch the pipeline with a gui *sometimes*. The cleanest way to do that would be to have some generic way of setting config params as cli arguments, could do something like that with click. but this also makes sense as a special case.

> there's another decision to make i.e. what do i do when when user says --no-gui but there are streaming nodes in the pipeline? 

Ideally the overhead would be small enough that it would be fine to run a pipeline without there being event listeners for specific kinds of events. So instead of having a special case for runnign without GUI where you go and filter out all the streaming nodes, it's no problem for them to be there doing nothing. 

How i would think of this is that "gui" isn't a boolean switch, but `LinePlot` and `VideoDisplay` are `Sink` nodes in the processing graph. If they are present and enabled, then they will set up whatever dependencies they need in their init methods (e.g. launching the fastapi server, etc.). Then `gui: true` is a shorthand for "add visualization sinks to all the processing nodes." Otherwise, if there is no listener for new line data, new video frame data, then those events get emitted at no/little cost and it's not a problem.

_Originally posted by @sneakers-the-rat in https://github.com/Aharoni-Lab/cala/pull/92#discussion_r2074378542_

**Comment by raymondwjang** [comment]
While working on this, there's an added complexity of nodes having to send config to frontend as they're getting initialized.

e.g. there are two types of configs being sent - one in lifespan startup, and the other in node setup. 
things like fps can belong in lifespan setup, since this is universal across all nodes that will deal with the frontend side.
however, traits like `frame_width` and `frame_height` isn't exactly so. it could be downsampled during the preprocessing stage, or the `FootprintStream` node might simply want to crop out uninteresting areas. additionally, the paths of the playlist and vidoe chunks will be different for each node as well. these must be set at the node initialization time, or pre-mapped somehow between backend and frontend.

similarly, for `LinePlotter`, each plot would want a different width and height, x and y limits, along with how many points to keep in stream.

for version alpha, i could technically freeze the dashboard so that we always have a certain set of streaming nodes (i.e. a single video streamer and a single metric streamer) but this would not be extendible without restructuring the config format. the ideal way to do this would be for each streaming node to have a `visual_setup` section of its config, where it can decide what kind of visualization it is (video or plot) and its traits.

i'm not yet entirely sure how i would dynamically connect the front and backend here. frontend and backend would need a shared lingo for `video_stream` and `line_plot`, etc., and some way to map the backend node to the frontend container or div. lastly, there needs to be a way to send the corresponding configs from backend (or from the config itself) and read them on the front.

**Comment by raymondwjang** [comment]
Seems llke having a suite of websockets might be the most straightforward solution

**Comment by raymondwjang** [comment]
ok, so the config should look something like:

```yaml
user_dir: .
output_dir: data/output

pipeline:
  preprocess:
    downsample:
      node: Denoiser
      params:
        method: gaussian
        kernel_size: 5
    motion_correction:
      node: RigidTranslator
      params:
        drift: 0.7
      requires: [ downsample ]
  
  iteration:
    footprint:
      node: FootprintUpdater
        params: ...
      ...
    footprint_video:
      node: FootprintPresser  # this should only take in footprints and output flattened footprint frame
      params: ...  # internal operation parameters
      requires: [ footprint ]
      sink:
        node: VideoDisplay  # sets up video stream and conveys configs to frontend, and actually does the streaming.
        params:
          width: 512
          height: 512
          fps: 30

    trace_plot:
      node: TraceChopper  # this should only take in traces and output the latest values
      params: ...  # internal operation parameters
      requires: [ trace ]
      sink:
        node: LinePlot  # sets up websocket and conveys configs to frontend, and actually does the streaming.
        params:
          width: 600
          height: 200
          max_points: 100
```

if `noob` deploys, instead of attaching `sink` to the `node`, i can point the output of `FootprintPresser` to the input of `VideoDisplay`. probably less to worry about the node building some internal method that takes the sink, initializes and run its methods, etc. in that case.

**Comment by raymondwjang** [comment]
with `noob` substituted in, it would look something closer to:

```yaml
    footprint_press:
      node: FootprintPresser  # this should only take in footprints and output flattened footprint frame
      params: ...  # internal operation parameters
      requires: [ footprint ]
      output: [ footprint_display: array ]

    footprint_display:
      node: VideoDisplay  # sets up video stream and conveys configs to frontend, and actually does the streaming.
      params:
        width: 512
        height: 512
        fps: 30
      requires: [ footprint_press ]

    trace_chop:
      node: TraceChopper  # this should only take in traces and output the latest values
      params: ...  # internal operation parameters
      requires: [ trace ]
      output: [ trace_lineplot: latest_vals ]

    trace_lineplot:
      node: LinePlot  # sets up websocket and conveys configs to frontend, and actually does the streaming.
      params:
        width: 600
        height: 200
        max_points: 100
      requires: [ trace_chop ]
```
