### ISSUE TITLE
First Iteration GUI Implementation Scoping

### ISSUE THREAD

**Issue by raymondwjang** [Aharoni-Lab/cala#97]
# Problem:

integrating **gui** nodes into the main procethis ssing pipeline presents a number of difficulties.
the original vision was to (and still eventually is) enable users to develop any kind of visualization nodes of their liking, plug it into config and run it, and it'll be displayed on dashboard automatically.

however, with the current runner-node design that directs all node return values to store, this implementation becomes rather cumbersome. the nodes have to be aware of the presence of an fastapi app, and what kinds of connections are available. it sometimes even has to notify the frontend about  nature of the data being emitted, so that the frontend can plot it properly.

# Proposal:
 
to circumvent these hurdles for the alpha release, we're temporarily sacrificing the user configurability. 
we assume two things:
1. 80/20: 80% of the use cases are covered by 20% of the features
2. it's difficult to imagine a scenario where a user is analyzing hours/days/weeks worth of data with absolutely no visualization. thus, we assume the users _**always**_ want some level of visualization.

based on these, we're going to compile a fixed set of data available for visualization. these sets of data will always be emitted through each runner process loop. this also means the frontend dashboard will be fixed, as well. The maximal amount of flexibility of the user that the alpha version will offer is possibly removing some of these plot options.

# Future:

as we move to integrate `noob` into `cala`, we can take advantage of `noob`'s capability for nodes to "request" runner to initialize external objects and inject its returns into specific slots. this then enables the broad vision of custom visualization node plug-in into the pipeline.

then, the user will be able to simply write up their own visualization node like:

```python
class MyViz:
    def fit(frame, footprints):
        ...
    def transform(frame):
        ...
```

and plug this straight into config like:
```yaml
pipeline:
  prep:
    denoise:
      node: cala.stream.nodes.prep.Denoiser

    ...

  iter:
    update_footprints:
      node: cala.stream.nodes.iter.FootprintUpdater

    ...

    plot_footprints:
      node: cala.stream.nodes.visual.MyViz
      depends: 
        footprints: update_footprints.array
```
